const mongoose = require('mongoose');
require('dotenv').config();

const mongoURI = process.env.MONGO_URI;

// Define the NEW, expanded product schema. This must match the one in server.js
const productSchema = new mongoose.Schema({
  name: { type: String, required: true },
  brand: { type: String, required: true },
  category: { type: String, required: true },
  price: { type: Number, required: true },
  mrp: { type: Number, required: true }, // Manufacturer's Retail Price
  rating: { type: Number, required: true, min: 0, max: 5 },
  ratingsCount: { type: String, required: true }, // e.g., "1.2L"
  boughtInPastMonth: { type: String, required: true }, // e.g., "600+"
  description: { type: String, required: true },
  warranty: { type: String, required: true },
  returnPolicy: { type: String, required: true },
  imageUrl: { type: String, default: '' }, // Will be populated by file uploads
});

const Product = mongoose.model('Product', productSchema);

// New, richer seed data for our products (20 total)
const seedProducts = [
    {
        name: 'Cross-Cut Paper Shredder',
        brand: 'Amazon Basics',
        category: 'Office Supplies',
        price: 4999,
        mrp: 6499,
        rating: 4.1,
        ratingsCount: '1.2L',
        boughtInPastMonth: '600',
        description: 'Amazon Basics 6-Sheet Cross Cut Paper and Credit Card Shredder with a 11.5 Liter waste basket capacity. Ideal for office and home usage, ensuring your sensitive information is securely disposed of.',
        warranty: '1 Year Brand Warranty',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760462173508-cross_cut.jpg',
    },
    {
        name: 'Galaxy Smart Watch 5',
        brand: 'Samsung',
        category: 'Electronics',
        price: 14999,
        mrp: 19999,
        rating: 4.6,
        ratingsCount: '8.5k',
        boughtInPastMonth: '1000',
        description: 'Track your fitness goals and stay connected with the world on your wrist. Features advanced sleep tracking, body composition analysis, and a durable sapphire crystal glass display.',
        warranty: '1 Year Manufacturer Warranty',
        returnPolicy: '7 Day Replacement',
        imageUrl: 'uploads/1760462152527-Galaxy Smart Watch 5.jpg',
    },
    {
        name: 'Noise Cancelling Headphones',
        brand: 'Sony',
        category: 'Electronics',
        price: 22500,
        mrp: 29990,
        rating: 4.8,
        ratingsCount: '22k',
        boughtInPastMonth: '2000',
        description: 'Industry-leading noise cancellation with Dual Noise Sensor technology. Enjoy up to 30 hours of battery life and crystal-clear hands-free calling. Perfect for travel, work, and immersive listening.',
        warranty: '1 Year Brand Warranty',
        returnPolicy: '7 Day Replacement',
        imageUrl: 'uploads/1760462112036-Noise Cancelling Headphones.jpg',
    },
    {
        name: 'Pro Gaming Laptop',
        brand: 'ASUS ROG',
        category: 'Computers',
        price: 129999,
        mrp: 145000,
        rating: 4.7,
        ratingsCount: '1.8k',
        boughtInPastMonth: '100',
        description: 'Unleash peak gaming performance with the latest Intel Core i9 processor and NVIDIA GeForce RTX 40-series graphics. A stunning 165Hz QHD display provides ultra-smooth and immersive visuals.',
        warranty: '2 Years International Warranty',
        returnPolicy: '7 Day Replacement',
        imageUrl: 'uploads/1760462125826-Pro Gaming Laptop.jpg',
    },
    {
        name: 'Automatic Drip Coffee Maker',
        brand: 'Philips',
        category: 'Home & Kitchen',
        price: 3495,
        mrp: 4995,
        rating: 4.3,
        ratingsCount: '6.2k',
        boughtInPastMonth: '400',
        description: 'Brews up to 12 cups of rich, aromatic coffee in minutes. Features an aroma twister for optimal taste and a drip-stop function to pour a cup anytime. The compact design fits perfectly on any countertop.',
        warranty: '2 Year Brand Warranty',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760462224988-Automatic Drip Coffee Maker.jpg',
    },
    {
        name: 'Men\'s Cotton Crew Neck T-Shirt',
        brand: 'Levi\'s',
        category: 'Fashion',
        price: 899,
        mrp: 1499,
        rating: 4.4,
        ratingsCount: '15k',
        boughtInPastMonth: '3000',
        description: 'A timeless classic for any wardrobe. Made from 100% premium soft cotton for maximum comfort and durability. Features the iconic brand logo on the chest.',
        warranty: 'No Warranty',
        returnPolicy: '30 Day Returnable',
        imageUrl: 'uploads/1760462195466-Men\'s Cotton Crew Neck T-Shirt.jpg',
    },
    {
        name: 'The Psychology of Money',
        brand: 'Morgan Housel',
        category: 'Books',
        price: 350,
        mrp: 599,
        rating: 4.7,
        ratingsCount: '55k',
        boughtInPastMonth: '5000',
        description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people.',
        warranty: 'N/A',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760462137975-The Psychology of Money.jpg',
    },
    {
        name: 'High-Density Yoga Mat',
        brand: 'Tego',
        category: 'Sports & Fitness',
        price: 1299,
        mrp: 2499,
        rating: 4.5,
        ratingsCount: '9k',
        boughtInPastMonth: '800',
        description: '6mm thick high-density foam mat provides the perfect balance of comfort and support. The non-slip surface ensures stability during any yoga posture or fitness routine.',
        warranty: '6 Month Warranty on Manufacturing Defects',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760462202835-High-Density Yoga Mat.jpg',
    },
    {
        name: 'iPhone 15 Pro',
        brand: 'Apple',
        category: 'Electronics',
        price: 134900,
        mrp: 134900,
        rating: 4.9,
        ratingsCount: '5k',
        boughtInPastMonth: '700',
        description: 'The ultimate iPhone experience. Featuring a strong and lightweight titanium design, the powerful A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
        warranty: '1 Year Manufacturer Warranty',
        returnPolicy: '7 Day Replacement',
        imageUrl: 'uploads/1760462103451-iPhone 15 Pro.jpg',
    },
    {
        name: '500W Mixer Grinder',
        brand: 'Prestige',
        category: 'Home & Kitchen',
        price: 2999,
        mrp: 4500,
        rating: 4.2,
        ratingsCount: '25k',
        boughtInPastMonth: '2000',
        description: 'A durable and efficient mixer grinder with 3 stainless steel jars for all your grinding needs. The powerful 500W motor can handle tough ingredients with ease.',
        warranty: '2 Year Warranty on Product, 5 Years on Motor',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760462084526-500W Mixer Grinder.jpg',
    },
    {
        name: 'Air Purifier for Home',
        brand: 'Coway',
        category: 'Home Appliances',
        price: 13500,
        mrp: 21900,
        rating: 4.6,
        ratingsCount: '11k',
        boughtInPastMonth: '500',
        description: 'Breathe clean, fresh air with the HEPA filter that captures 99.97% of airborne pollutants. Ideal for bedrooms and living rooms, with a smart auto mode that adjusts fan speed based on air quality.',
        warranty: '1 Year Warranty on Product, 5 Years on Motor',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760462054277-Air Purifier for Home.jpg',
    },
    {
        name: 'Portable Bluetooth Speaker',
        brand: 'JBL',
        category: 'Electronics',
        price: 3199,
        mrp: 4999,
        rating: 4.5,
        ratingsCount: '1.5L',
        boughtInPastMonth: '10000',
        description: 'Enjoy powerful, room-filling sound on the go. This speaker is IP67 waterproof and dustproof, offering up to 12 hours of playtime on a single charge.',
        warranty: '1 Year Brand Warranty',
        returnPolicy: '7 Day Replacement',
        imageUrl: 'uploads/1760461901770-Portable Bluetooth Speaker.jpg',
    },
    {
        name: 'Men\'s Slim Fit Jeans',
        brand: 'U.S. Polo Assn.',
        category: 'Fashion',
        price: 1799,
        mrp: 3599,
        rating: 4.3,
        ratingsCount: '12k',
        boughtInPastMonth: '1000',
        description: 'Crafted from premium stretch denim for a perfect fit and all-day comfort. A versatile wardrobe staple that can be dressed up or down for any occasion.',
        warranty: 'No Warranty',
        returnPolicy: '30 Day Returnable',
        imageUrl: 'uploads/1760461872743-Men\'s Slim Fit Jeans.jpg',
    },
    {
        name: 'Atomic Habits',
        brand: 'James Clear',
        category: 'Books',
        price: 410,
        mrp: 799,
        rating: 4.8,
        ratingsCount: '95k',
        boughtInPastMonth: '8000',
        description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. This book offers a practical framework for improving every day. A must-read for anyone looking for self-improvement.',
        warranty: 'N/A',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760462065877-Atomic Habits.jpg',
    },
    {
        name: 'Electric Oral Toothbrush',
        brand: 'Oral-B',
        category: 'Personal Care',
        price: 2199,
        mrp: 3200,
        rating: 4.5,
        ratingsCount: '45k',
        boughtInPastMonth: '4000',
        description: 'Removes up to 100% more plaque than a regular manual toothbrush. The built-in 2-minute timer helps you brush for the dentist-recommended time.',
        warranty: '2 Year Brand Warranty',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760461841101-Electric Oral Toothbrush.jpg',
    },
    {
        name: 'EOS 200D II DSLR Camera',
        brand: 'Canon',
        category: 'Electronics',
        price: 58990,
        mrp: 69995,
        rating: 4.6,
        ratingsCount: '3.5k',
        boughtInPastMonth: '200',
        description: 'Capture stunning high-quality photos and 4K videos with this compact and easy-to-use DSLR. Features a vari-angle touchscreen and dual pixel CMOS AF for fast, accurate focusing.',
        warranty: '2 Year Brand Warranty',
        returnPolicy: '7 Day Replacement',
        imageUrl: 'uploads/1760461833039-EOS 200D II DSLR Camera.jpg',
    },
    {
        name: 'UNO Playing Card Game',
        brand: 'Mattel',
        category: 'Toys & Games',
        price: 199,
        mrp: 299,
        rating: 4.6,
        ratingsCount: '1.2L',
        boughtInPastMonth: '10000',
        description: 'The classic card game of matching colors and numbers that\'s easy to pick up but impossible to put down. Fun for the whole family!',
        warranty: 'No Warranty',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760461820125-UNO Playing Card Game.jpg',
    },
    {
        name: '20kg Dumbbell Set (10kg x 2)',
        brand: 'Kore',
        category: 'Sports & Fitness',
        price: 1499,
        mrp: 3000,
        rating: 4.0,
        ratingsCount: '35k',
        boughtInPastMonth: '1000',
        description: 'A complete home gym set with rubberized plates and chrome-plated rods. Perfect for strength training, muscle building, and toning.',
        warranty: 'No Warranty',
        returnPolicy: '10 Day Returnable',
        imageUrl: 'uploads/1760461810219-20kg Dumbbell Set (10kg x 2).jpg',
    },
    {
        name: '10.9-inch iPad (10th Gen)',
        brand: 'Apple',
        category: 'Computers',
        price: 33900,
        mrp: 34900,
        rating: 4.7,
        ratingsCount: '2.1k',
        boughtInPastMonth: '300',
        description: 'The all-new colorful iPad for the things you do every day. Features a stunning 10.9-inch Liquid Retina display and the powerful A14 Bionic chip for incredible performance.',
        warranty: '1 Year Manufacturer Warranty',
        returnPolicy: '7 Day Replacement',
        imageUrl: 'uploads/1760461801014-10.9-inch iPad (10th Gen).jpg',
    },
    {
        name: 'Organic India Green Tea',
        brand: 'Organic India',
        category: 'Groceries',
        price: 234,
        mrp: 260,
        rating: 4.5,
        ratingsCount: '40k',
        boughtInPastMonth: '6000',
        description: 'Enjoy the health benefits of this refreshing and antioxidant-rich green tea. Made from the finest organic Tulsi leaves to boost immunity and reduce stress.',
        warranty: 'N/A',
        returnPolicy: 'Non-Returnable',
        imageUrl: 'uploads/1760461779482-Organic India Green Tea.jpg',
    },
];


const seedDB = async () => {
  try {
    await mongoose.connect(mongoURI, { useNewUrlParser: true, useUnifiedTopology: true });
    console.log('MongoDB connected for seeding...');

    // Clear existing products to avoid duplicates
    await Product.deleteMany({});
    console.log('Existing products cleared.');

    // Insert the new, enhanced product data
    await Product.insertMany(seedProducts);
    console.log('Database has been successfully seeded with new data!');

  } catch (err) {
    console.error('Seeding error:', err);
  } finally {
    // Close the connection after the script is done
    await mongoose.connection.close();
    console.log('MongoDB connection closed.');
  }
};

// Run the seeder function
seedDB();